import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from 'next/font/google'


import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";


// Configure the font with weights, styles, and subsets
const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200', '400', '600', '800'],
  variable: '--font-jakarta', // optional CSS variable
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.className} antialiased`}
      >
       <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
