export interface Job {
  id: string;
  company: string;
  companyLogo: string;
  title: string;
  location: string;
  type: string;
  postedDate: string;
  skills: string[];
  category: string;
  categoryId: string;
  featured: boolean;
  salary: string;
  experience: string;
  description: string;
}

const ALL_JOBS = [
  {
    id: "1",
    company: "Outlier",
    companyLogo: "https://logo.clearbit.com/outlier.org",
    title: "Spanish (Mexico) Freelance Writer",
    location: "Remote",
    type: "Project-based",
    postedDate: "04 Jan",
    skills: ["Writing", "es Spanish"],
    category: "Humanities & Social Sciences",
    categoryId: "humanities",
    featured: true,
    salary: "$45-65/hr",
    experience: "Mid Level",
    description: "Create engaging educational content for our Spanish-language courses focused on Mexico."
  },
  {
    id: "2",
    company: "Outlier",
    companyLogo: "https://logo.clearbit.com/outlier.org",
    title: "Arabic (Egypt) Freelance Writer",
    location: "Remote",
    type: "Project-based",
    postedDate: "04 Jan",
    skills: ["Writing", "ar Arabic"],
    category: "Humanities & Social Sciences",
    categoryId: "humanities",
    featured: true,
    salary: "$45-65/hr",
    experience: "Mid Level",
    description: "Develop educational materials in Arabic tailored for Egyptian audiences."
  },
  {
    id: "3",
    company: "Outlier",
    companyLogo: "https://logo.clearbit.com/outlier.org",
    title: "French Freelance Writer",
    location: "Remote",
    type: "Project-based",
    postedDate: "03 Jan",
    skills: ["Writing", "fr French"],
    category: "Humanities & Social Sciences",
    categoryId: "humanities",
    featured: false,
    salary: "$45-65/hr",
    experience: "Mid Level",
    description: "Create educational content in French for our international course offerings."
  },
  {
    id: "4",
    company: "RemoteNext",
    companyLogo: "https://logo.clearbit.com/remotenext.io",
    title: "Senior React Developer",
    location: "Remote",
    type: "Full-time",
    postedDate: "05 Jan",
    skills: ["React", "TypeScript", "NextJS"],
    category: "Software Development",
    categoryId: "software-dev",
    featured: true,
    salary: "$120K-160K",
    experience: "Senior Level",
    description: "Build and improve our job platform using modern React and NextJS frameworks."
  },
  {
    id: "5",
    company: "TechGlobal",
    companyLogo: "https://logo.clearbit.com/techglobal.com",
    title: "UX/UI Designer",
    location: "Remote",
    type: "Contract",
    postedDate: "02 Jan",
    skills: ["Figma", "Design Systems", "User Research"],
    category: "Design",
    categoryId: "design",
    featured: false,
    salary: "$85K-110K",
    experience: "Mid Level",
    description: "Create intuitive user experiences and visually appealing interfaces for our SaaS products."
  },
  {
    id: "6",
    company: "HealthTech",
    companyLogo: "https://logo.clearbit.com/healthtech.com",
    title: "Medical Content Writer",
    location: "Remote",
    type: "Project-based",
    postedDate: "06 Jan",
    skills: ["Medical Writing", "Research", "Content Strategy"],
    category: "Healthcare",
    categoryId: "healthcare",
    featured: true,
    salary: "$60-80/hr",
    experience: "Senior Level",
    description: "Produce accurate and engaging health content for our digital platforms."
  },
  {
    id: "7",
    company: "DataViz Inc",
    companyLogo: "https://logo.clearbit.com/dataviz.com",
    title: "Data Scientist",
    location: "Hybrid",
    type: "Full-time",
    postedDate: "01 Jan",
    skills: ["Python", "TensorFlow", "Data Visualization"],
    category: "Data Science & Analytics",
    categoryId: "data-science",
    featured: true,
    salary: "$130K-160K",
    experience: "Senior Level",
    description: "Apply machine learning and statistical techniques to extract insights from large datasets."
  },
  {
    id: "8",
    company: "SecureNet",
    companyLogo: "https://logo.clearbit.com/securenet.io",
    title: "Cybersecurity Analyst",
    location: "Remote",
    type: "Full-time",
    postedDate: "03 Jan",
    skills: ["Threat Detection", "Security Tools", "Incident Response"],
    category: "Cybersecurity",
    categoryId: "cybersecurity",
    featured: false,
    salary: "$95K-120K",
    experience: "Mid Level",
    description: "Monitor and protect our systems from security threats and vulnerabilities."
  },
  {
    id: "9",
    company: "CloudNative",
    companyLogo: "https://logo.clearbit.com/cloudnative.dev",
    title: "DevOps Engineer",
    location: "Remote",
    type: "Full-time",
    postedDate: "05 Jan",
    skills: ["AWS", "Kubernetes", "CI/CD"],
    category: "Cloud & DevOps",
    categoryId: "cloud-devops",
    featured: true,
    salary: "$115K-145K",
    experience: "Senior Level",
    description: "Build and maintain our cloud infrastructure and deployment pipelines."
  },
  {
    id: "10",
    company: "TechGrowth",
    companyLogo: "https://logo.clearbit.com/techgrowth.com",
    title: "Growth Marketing Lead",
    location: "Remote",
    type: "Full-time",
    postedDate: "02 Jan",
    skills: ["Growth Strategy", "Analytics", "Marketing Automation"],
    category: "Marketing & Growth",
    categoryId: "marketing",
    featured: false,
    salary: "$90K-120K",
    experience: "Lead",
    description: "Drive user acquisition and engagement through data-driven growth strategies."
  },
  {
    id: "11",
    company: "AIVentures",
    companyLogo: "https://logo.clearbit.com/aiventures.ai",
    title: "AI Research Scientist",
    location: "Remote",
    type: "Full-time",
    postedDate: "03 Jan",
    skills: ["Deep Learning", "NLP", "Research"],
    category: "AI & Machine Learning",
    categoryId: "ai-ml",
    featured: true,
    salary: "$150K-180K",
    experience: "Senior Level",
    description: "Conduct cutting-edge research in artificial intelligence and machine learning."
  },
  {
    id: "12",
    company: "ProductFirst",
    companyLogo: "https://logo.clearbit.com/productfirst.io",
    title: "Senior Product Manager",
    location: "Hybrid",
    type: "Full-time",
    postedDate: "04 Jan",
    skills: ["Product Strategy", "User Stories", "Roadmapping"],
    category: "Product Management",
    categoryId: "product-management",
    featured: true,
    salary: "$130K-160K",
    experience: "Senior Level",
    description: "Lead product development from conception to launch, working with cross-functional teams."
  },
  {
    id: "13",
    company: "EduTech",
    companyLogo: "https://logo.clearbit.com/edutech.edu",
    title: "Online Course Developer",
    location: "Remote",
    type: "Contract",
    postedDate: "01 Jan",
    skills: ["Instructional Design", "E-Learning", "Content Creation"],
    category: "Education",
    categoryId: "education",
    featured: false,
    salary: "$40-60/hr",
    experience: "Mid Level",
    description: "Create engaging online courses with a focus on technical skills and professional development."
  },
  {
    id: "14",
    company: "FinTechNow",
    companyLogo: "https://logo.clearbit.com/fintechnow.com",
    title: "Financial Analyst",
    location: "Remote",
    type: "Full-time",
    postedDate: "02 Jan",
    skills: ["Financial Modeling", "Analysis", "Reporting"],
    category: "Finance",
    categoryId: "finance",
    featured: false,
    salary: "$85K-105K",
    experience: "Mid Level",
    description: "Analyze financial data and prepare reports to guide business decisions."
  },
  {
    id: "15",
    company: "PeopleFirst",
    companyLogo: "https://logo.clearbit.com/peoplefirst.hr",
    title: "Remote Work Culture Specialist",
    location: "Remote",
    type: "Full-time",
    postedDate: "05 Jan",
    skills: ["Culture Development", "Employee Engagement", "Remote Work"],
    category: "Human Resources",
    categoryId: "hr",
    featured: true,
    salary: "$90K-110K",
    experience: "Mid Level",
    description: "Develop and implement strategies to foster a strong remote work culture."
  },
  {
    id: "16",
    company: "CustomerWin",
    companyLogo: "https://logo.clearbit.com/customerwin.io",
    title: "Customer Success Manager",
    location: "Remote",
    type: "Full-time",
    postedDate: "03 Jan",
    skills: ["Customer Relationship", "SaaS", "Onboarding"],
    category: "Customer Success",
    categoryId: "customer-success",
    featured: false,
    salary: "$80K-100K",
    experience: "Mid Level",
    description: "Ensure customer satisfaction and retention by providing exceptional support and guidance."
  },
  {
    id: "17",
    company: "SalesForce",
    companyLogo: "https://logo.clearbit.com/salesforce.com",
    title: "Enterprise Sales Executive",
    location: "Remote",
    type: "Full-time",
    postedDate: "04 Jan",
    skills: ["Enterprise Sales", "Solution Selling", "CRM"],
    category: "Sales",
    categoryId: "sales",
    featured: true,
    salary: "$110K-150K + Commission",
    experience: "Senior Level",
    description: "Drive revenue growth by selling our enterprise solutions to large organizations."
  },
  {
    id: "18",
    company: "MobileDev",
    companyLogo: "https://logo.clearbit.com/mobiledev.io",
    title: "React Native Developer",
    location: "Remote",
    type: "Contract",
    postedDate: "01 Jan",
    skills: ["React Native", "JavaScript", "Mobile Development"],
    category: "Software Development",
    categoryId: "software-dev",
    featured: false,
    salary: "$70-90/hr",
    experience: "Mid Level",
    description: "Develop cross-platform mobile applications using React Native."
  }
];

export default ALL_JOBS;
